version: "3.7"

services:

  clef-1:
    image: ethersphere/clef:0.4.12
    restart: unless-stopped
    privileged: true
    environment:
      - CLEF_CHAINID
    volumes:
      - /data/docker/clef1:/app/data
    user: root
    command: full

  bee-1:
    image: ethersphere/bee:latest
    restart: unless-stopped
    environment:
      - BEE_API_ADDR
      - BEE_BOOTNODE
      - BEE_CLEF_SIGNER_ENABLE
      - BEE_CLEF_SIGNER_ENDPOINT=http://clef-1:8550
      - BEE_CONFIG
      - BEE_CORS_ALLOWED_ORIGINS
      - BEE_DATA_DIR
      - BEE_DB_CAPACITY
      - BEE_DEBUG_API_ADDR
      - BEE_DEBUG_API_ENABLE
      - BEE_GATEWAY_MODE
      - BEE_GLOBAL_PINNING_ENABLE
      - BEE_NAT_ADDR
      - BEE_NETWORK_ID
      - BEE_P2P_ADDR
      - BEE_P2P_QUIC_ENABLE
      - BEE_P2P_WS_ENABLE
      - BEE_PASSWORD
      - BEE_PASSWORD_FILE
      - BEE_PAYMENT_EARLY
      - BEE_PAYMENT_THRESHOLD
      - BEE_PAYMENT_TOLERANCE
      - BEE_RESOLVER_OPTIONS
      - BEE_STANDALONE
      - BEE_SWAP_ENABLE
      - BEE_SWAP_ENDPOINT
      - BEE_SWAP_FACTORY_ADDRESS
      - BEE_SWAP_INITIAL_DEPOSIT
      - BEE_TRACING_ENABLE
      - BEE_TRACING_ENDPOINT
      - BEE_TRACING_SERVICE_NAME
      - BEE_VERBOSITY
      - BEE_WELCOME_MESSAGE
    ports:
      - "${API_ADDR:-1793}${BEE_API_ADDR:-:1633}"
      - "${P2P_ADDR:-1794}${BEE_P2P_ADDR:-:1634}"
      - "${DEBUG_API_ADDR:-1795}${BEE_DEBUG_API_ADDR:-:1635}"
    volumes:
      - /data/docker/bee1:/home/bee/.bee
    deploy:
      resources:
        limits:
          cpus: '1.60'
    user: root
    command: start
    depends_on:
      - clef-1

  clef-2:
    image: ethersphere/clef:0.4.12
    restart: unless-stopped
    privileged: true
    environment:
      - CLEF_CHAINID
    volumes:
      - /data/docker/clef2:/app/data
    user: root
    command: full
    
  bee-2:
    image: ethersphere/bee:latest
    restart: unless-stopped
    environment:
      - BEE_API_ADDR
      - BEE_BOOTNODE
      - BEE_CLEF_SIGNER_ENABLE
      - BEE_CLEF_SIGNER_ENDPOINT=http://clef-2:8550
      - BEE_CONFIG
      - BEE_CORS_ALLOWED_ORIGINS
      - BEE_DATA_DIR
      - BEE_DB_CAPACITY
      - BEE_DEBUG_API_ADDR
      - BEE_DEBUG_API_ENABLE
      - BEE_GATEWAY_MODE
      - BEE_GLOBAL_PINNING_ENABLE
      - BEE_NAT_ADDR
      - BEE_NETWORK_ID
      - BEE_P2P_ADDR
      - BEE_P2P_QUIC_ENABLE
      - BEE_P2P_WS_ENABLE
      - BEE_PASSWORD
      - BEE_PASSWORD_FILE
      - BEE_PAYMENT_EARLY
      - BEE_PAYMENT_THRESHOLD
      - BEE_PAYMENT_TOLERANCE
      - BEE_RESOLVER_OPTIONS
      - BEE_STANDALONE
      - BEE_SWAP_ENABLE
      - BEE_SWAP_ENDPOINT
      - BEE_SWAP_FACTORY_ADDRESS
      - BEE_SWAP_INITIAL_DEPOSIT
      - BEE_TRACING_ENABLE
      - BEE_TRACING_ENDPOINT
      - BEE_TRACING_SERVICE_NAME
      - BEE_VERBOSITY
      - BEE_WELCOME_MESSAGE
    ports:
      - "${API_ADDR:-1893}${BEE_API_ADDR:-:1633}"
      - "${P2P_ADDR:-1894}${BEE_P2P_ADDR:-:1634}"
      - "${DEBUG_API_ADDR:-1895}${BEE_DEBUG_API_ADDR:-:1635}"
    volumes:
      - /data/docker/bee2:/home/bee/.bee
    deploy:
      resources:
        limits:
          cpus: '1.60'
    user: root
    command: start
    depends_on:
      - clef-2

  clef-3:
    image: ethersphere/clef:0.4.12
    restart: unless-stopped
    privileged: true
    environment:
      - CLEF_CHAINID
    volumes:
      - /data/docker/clef3:/app/data
    user: root
    command: full
    
  bee-3:
    image: ethersphere/bee:latest
    restart: unless-stopped
    environment:
      - BEE_API_ADDR
      - BEE_BOOTNODE
      - BEE_CLEF_SIGNER_ENABLE
      - BEE_CLEF_SIGNER_ENDPOINT=http://clef-3:8550
      - BEE_CONFIG
      - BEE_CORS_ALLOWED_ORIGINS
      - BEE_DATA_DIR
      - BEE_DB_CAPACITY
      - BEE_DEBUG_API_ADDR
      - BEE_DEBUG_API_ENABLE
      - BEE_GATEWAY_MODE
      - BEE_GLOBAL_PINNING_ENABLE
      - BEE_NAT_ADDR
      - BEE_NETWORK_ID
      - BEE_P2P_ADDR
      - BEE_P2P_QUIC_ENABLE
      - BEE_P2P_WS_ENABLE
      - BEE_PASSWORD
      - BEE_PASSWORD_FILE
      - BEE_PAYMENT_EARLY
      - BEE_PAYMENT_THRESHOLD
      - BEE_PAYMENT_TOLERANCE
      - BEE_RESOLVER_OPTIONS
      - BEE_STANDALONE
      - BEE_SWAP_ENABLE
      - BEE_SWAP_ENDPOINT
      - BEE_SWAP_FACTORY_ADDRESS
      - BEE_SWAP_INITIAL_DEPOSIT
      - BEE_TRACING_ENABLE
      - BEE_TRACING_ENDPOINT
      - BEE_TRACING_SERVICE_NAME
      - BEE_VERBOSITY
      - BEE_WELCOME_MESSAGE
    ports:
      - "${API_ADDR:-1993}${BEE_API_ADDR:-:1633}"
      - "${P2P_ADDR:-1994}${BEE_P2P_ADDR:-:1634}"
      - "${DEBUG_API_ADDR:-1995}${BEE_DEBUG_API_ADDR:-:1635}"
    volumes:
      - /data/docker/bee3:/home/bee/.bee
    deploy:
      resources:
        limits:
          cpus: '1.60'
    user: root
    command: start
    depends_on:
      - clef-3

  clef-4:
    image: ethersphere/clef:0.4.12
    restart: unless-stopped
    privileged: true
    environment:
      - CLEF_CHAINID
    volumes:
      - /data/docker/clef4:/app/data
    user: root
    command: full
    
  bee-4:
    image: ethersphere/bee:latest
    restart: unless-stopped
    environment:
      - BEE_API_ADDR
      - BEE_BOOTNODE
      - BEE_CLEF_SIGNER_ENABLE
      - BEE_CLEF_SIGNER_ENDPOINT=http://clef-4:8550
      - BEE_CONFIG
      - BEE_CORS_ALLOWED_ORIGINS
      - BEE_DATA_DIR
      - BEE_DB_CAPACITY
      - BEE_DEBUG_API_ADDR
      - BEE_DEBUG_API_ENABLE
      - BEE_GATEWAY_MODE
      - BEE_GLOBAL_PINNING_ENABLE
      - BEE_NAT_ADDR
      - BEE_NETWORK_ID
      - BEE_P2P_ADDR
      - BEE_P2P_QUIC_ENABLE
      - BEE_P2P_WS_ENABLE
      - BEE_PASSWORD
      - BEE_PASSWORD_FILE
      - BEE_PAYMENT_EARLY
      - BEE_PAYMENT_THRESHOLD
      - BEE_PAYMENT_TOLERANCE
      - BEE_RESOLVER_OPTIONS
      - BEE_STANDALONE
      - BEE_SWAP_ENABLE
      - BEE_SWAP_ENDPOINT
      - BEE_SWAP_FACTORY_ADDRESS
      - BEE_SWAP_INITIAL_DEPOSIT
      - BEE_TRACING_ENABLE
      - BEE_TRACING_ENDPOINT
      - BEE_TRACING_SERVICE_NAME
      - BEE_VERBOSITY
      - BEE_WELCOME_MESSAGE
    ports:
      - "${API_ADDR:-2093}${BEE_API_ADDR:-:1633}"
      - "${P2P_ADDR:-2094}${BEE_P2P_ADDR:-:1634}"
      - "${DEBUG_API_ADDR:-2095}${BEE_DEBUG_API_ADDR:-:1635}"
    volumes:
      - /data/docker/bee4:/home/bee/.bee
    deploy:
      resources:
        limits:
          cpus: '1.60'
    user: root
    command: start
    depends_on:
      - clef-4

  clef-5:
    image: ethersphere/clef:0.4.12
    restart: unless-stopped
    privileged: true
    environment:
      - CLEF_CHAINID
    volumes:
      - /data/docker/clef5:/app/data
    user: root
    command: full
    
  bee-5:
    image: ethersphere/bee:latest
    restart: unless-stopped
    environment:
      - BEE_API_ADDR
      - BEE_BOOTNODE
      - BEE_CLEF_SIGNER_ENABLE
      - BEE_CLEF_SIGNER_ENDPOINT=http://clef-5:8550
      - BEE_CONFIG
      - BEE_CORS_ALLOWED_ORIGINS
      - BEE_DATA_DIR
      - BEE_DB_CAPACITY
      - BEE_DEBUG_API_ADDR
      - BEE_DEBUG_API_ENABLE
      - BEE_GATEWAY_MODE
      - BEE_GLOBAL_PINNING_ENABLE
      - BEE_NAT_ADDR
      - BEE_NETWORK_ID
      - BEE_P2P_ADDR
      - BEE_P2P_QUIC_ENABLE
      - BEE_P2P_WS_ENABLE
      - BEE_PASSWORD
      - BEE_PASSWORD_FILE
      - BEE_PAYMENT_EARLY
      - BEE_PAYMENT_THRESHOLD
      - BEE_PAYMENT_TOLERANCE
      - BEE_RESOLVER_OPTIONS
      - BEE_STANDALONE
      - BEE_SWAP_ENABLE
      - BEE_SWAP_ENDPOINT
      - BEE_SWAP_FACTORY_ADDRESS
      - BEE_SWAP_INITIAL_DEPOSIT
      - BEE_TRACING_ENABLE
      - BEE_TRACING_ENDPOINT
      - BEE_TRACING_SERVICE_NAME
      - BEE_VERBOSITY
      - BEE_WELCOME_MESSAGE
    ports:
      - "${API_ADDR:-2193}${BEE_API_ADDR:-:1633}"
      - "${P2P_ADDR:-2194}${BEE_P2P_ADDR:-:1634}"
      - "${DEBUG_API_ADDR:-2195}${BEE_DEBUG_API_ADDR:-:1635}"
    volumes:
      - /data/docker/bee5:/home/bee/.bee
    deploy:
      resources:
        limits:
          cpus: '1.60'
    user: root
    command: start
    depends_on:
      - clef-5

volumes:
  clef-1:
  bee-1:
  clef-2:
  bee-2:
  clef-3:
  bee-3:
  clef-4:
  bee-4:
  clef-5:
  bee-5: